services:
    web:
        build: .
        ports:
            - "8000:8000"
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        depends_on:
            -   db

    db:
        image: postgres:16
        volumes:
            -   postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
            - "POSTGRES_PASSWORD=postgres"
            - "POSTGRES_USER=postgres"
            - "POSTGRES_HOST=db"

volumes:
    postgres_data:
